<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Ryz1.SimCore</AssemblyName>
    <RootNamespace>Ryz1.SimCore</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ryz1.Contracts/Ryz1.Contracts.csproj" />
  </ItemGroup>
</Project>
